CREATE TABLE "MANIAS"(
"NO" NUMBER(9,0) NOT NULL,
"ID" VARCHAR2(20) NOT NULL,
"PASSWORD" VARCHAR2(32) NOT NULL,
"NICKNAME" VARCHAR2(50) NOT NULL,
"PROFILE" VARCHAR2(400) DEFAULT 'default.png' NOT NULL,
"REGDATE" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
CONSTRAINT "MANIAS_PK" PRIMARY KEY ("NO") ENABLE);

CREATE SEQUENCE "MANIAS_SEQ"
start with 1
increment by 1
maxvalue 9999999999999999999
minvalue 1
nocache
nocycle
noorder;

CREATE table "GENRES" (
"NO" NUMBER(8,0) NOT NULL,
"NAME" VARCHAR2(100) NOT NULL,
"MANIA_NO" NUMBER(9,0) NOT NULL,
"MOVIE_COUNT" NUMBER(10,0) NOT NULL,
"REGDATE" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
CONSTRAINT "GENRES_PK" PRIMARY KEY ("NO") ENABLE);

ALTER TABLE "GENRES" ADD CONSTRAINT "GENRES_FK" FOREIGN KEY ("MANIA_NO") REFERENCES "MANIAS" ("NO") ENABLE;

CREATE SEQUENCE "GENRES_SEQ"
start with 1
increment by 1
maxvalue 9999999999999999999
minvalue 1
nocache
nocycle
noorder;

CREATE TABLE  "MOVIES" (
"NO" NUMBER(9,0) NOT NULL ENABLE, 
"TITLE" VARCHAR2(400) NOT NULL ENABLE,
"ENG_TITLE" VARCHAR2(400),
"RELEASE_DATE" DATE NOT NULL ENABLE, 
"STATE" CHAR(1) NOT NULL ENABLE, 
"DIRECTOR" VARCHAR2(1000) NOT NULL ENABLE,
"ACTORS" VARCHAR2(2000) NOT NULL ENABLE,
"SUMMARY" VARCHAR2(4000) NOT NULL ENABLE,
"RATING" CHAR(1) NOT NULL ENABLE, 
"POSTER" VARCHAR2(400) DEFAULT 'default.png' NOT NULL,
"MANIA_NO" NUMBER(9,0) NOT NULL,
"REGDATE" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
CONSTRAINT "MOVIES_PK" PRIMARY KEY ("NO") ENABLE);

ALTER TABLE "MOVIES" ADD CONSTRAINT "MOVIES_FK" FOREIGN KEY ("MANIA_NO") REFERENCES  "MANIAS" ("NO") ENABLE;

CREATE SEQUENCE "MOVIES_SEQ"
start with 1
increment by 1
maxvalue 9999999999999999999
minvalue 1
nocache
nocycle
noorder;

CREATE table "MOVIE_GENRES" (
"NO" NUMBER(9,0) NOT NULL,
"GENRE_NO" NUMBER(8,0) NOT NULL,
"MOVIE_NO" NUMBER(9,0) NOT NULL,
"REGDATE" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
CONSTRAINT "MOVIE_GENRE_PK" PRIMARY KEY ("NO") ENABLE);

ALTER TABLE "MOVIE_GENRES" ADD CONSTRAINT "MOVIE_GENRES_FK" FOREIGN KEY ("GENRE_NO") REFERENCES  "GENRES" ("NO") ENABLE;
ALTER TABLE "MOVIE_GENRES" ADD CONSTRAINT "MOVIE_GENRES_FK2" FOREIGN KEY ("MOVIE_NO") REFERENCES  "MOVIES" ("NO") ENABLE;

CREATE SEQUENCE "MOVIE_GENRES_SEQ"
start with 1
increment by 1
maxvalue 9999999999999999999
minvalue 1
nocache
nocycle
noorder;

