CREATE TABLE "USERS"
( "NO" NUMBER(8,0) NOT NULL ENABLE,
"ID" VARCHAR2(20) NOT NULL ENABLE,
"PASSWORD" VARCHAR2(30) NOT NULL ENABLE,
"NICKNAME" VARCHAR2(30) NOT NULL ENABLE,
"REGDATE" TIMESTAMP NOT NULL ENABLE,
CONSTRAINT "USERS_PK" PRIMARY KEY ("NO") ENABLE
) ;

create sequence "USERS_SEQ"
start with 1
increment by 1
maxvalue 999999999
minvalue 1
nocache
nocycle
noorder;

CREATE TABLE "GUESTBOOK"
( "NO" NUMBER(8,0) NOT NULL ENABLE,
"WRITER" VARCHAR2(100) NOT NULL ENABLE,
"CONTENTS" VARCHAR2(420) NOT NULL ENABLE,
"REGDATE" TIMESTAMP NOT NULL ENABLE,
"IP" VARCHAR2(15) NOT NULL ENABLE,
"USER_NO" NUMBER(8,0) NOT NULL ENABLE,
CONSTRAINT "GUESTBOOKS_PK" PRIMARY KEY ("NO") ENABLE
) ;

ALTER TABLE "GUESTBOOK" ADD CONSTRAINT "GUESTBOOK_FK"
FOREIGN KEY ("USER_NO")
REFERENCES "USERS" ("NO");

CREATE SEQUENCE "GUESTBOOK_SEQ"
start with 1
increment by 1
maxvalue 9999999999999999999
minvalue 1
nocache
nocycle
noorder; 
